/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/iphone.glb')
  return (
    <group {...props} scale={0.2} dispose={null} style={{transform: "translateY(-100px)"}}>
      <mesh geometry={nodes.Extrude_1.geometry} material={materials['Wall Tiles 09 - Rock']} />
    </group>
  )
}

useGLTF.preload('/iphone.glb')

